---
- hosts: docker_server
  tasks:

  - name: Install Docker
    vars:
      ansible_python_interpreter: /usr/bin/python
    yum: 
      name: docker
      update_cache: yes
      state: present

  - name: Install / Download docker-compose
    # become: yes //play the task as a root user  
    get_url:
      url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-{{lookup('pipe','uname -m')}} 
      dest: /usr/local/bin/docker-compose
      mode: +x

  - name: Start docker daemon/service
    service:
      name: docker
      state: reloaded
      enabled: true
  - name: Install docker python module 
    pip: 
      name: 
      - docker
      - docker-compose 
  
  # Test 
  # - name: Test docker pull
  #   docker_image:
  #     name: redis 
  #     source: pull

  - name: Copy docker compose to Destination
    copy:
      src: /root/ansible/jenkins
      dest: /root/    

  - name: Start container from docker-compose file
    docker-compose:
      project_src: /root/jenkins/jenkins.yaml